# version: "3"

services:
  app:
    container_name: svctracker-10
    build:
      context: .
      dockerfile: Dockerfile.prod
    # env_file:
    #   - .env
    # volumes:
    #   - ".:/app"
    ports:
      - 7045:8080
